import type { WireframeFrame, WireframeElement } from '@/types'

// ─── HTML export ────────────────────────────────────────────────────────────

const ELEMENT_STYLE: Record<WireframeElement['type'], { bg: string; border: string; color: string; tag: string }> = {
  header:  { bg: '#e9f0ea', border: '#2e6b48', color: '#234e36', tag: 'header' },
  nav:     { bg: '#e9f0ea', border: '#2e6b48', color: '#234e36', tag: 'nav' },
  sidebar: { bg: '#f0f3f7', border: '#3a6ea5', color: '#253d5c', tag: 'aside' },
  main:    { bg: '#f9f9f8', border: '#d0d0c8', color: '#6b6b64', tag: 'main' },
  hero:    { bg: '#f2f2ef', border: '#b0b0a8', color: '#4a4a44', tag: 'section' },
  footer:  { bg: '#f0f0ec', border: '#b0b0a8', color: '#6b6b64', tag: 'footer' },
  card:    { bg: '#ffffff', border: '#c8c8c0', color: '#1a1a17', tag: 'article' },
  chart:   { bg: '#eef7f1', border: '#6a994e', color: '#2e5a1e', tag: 'figure' },
  table:   { bg: '#fafaf8', border: '#c8c8c0', color: '#1a1a17', tag: 'section' },
  form:    { bg: '#fafaf8', border: '#3a6ea5', color: '#253d5c', tag: 'form' },
  list:    { bg: '#fafaf8', border: '#c8c8c0', color: '#1a1a17', tag: 'section' },
  modal:   { bg: '#ffffff', border: '#2e6b48', color: '#1a1a17', tag: 'dialog' },
  grid:    { bg: '#f9f9f8', border: '#d0d0c8', color: '#6b6b64', tag: 'section' },
  button:  { bg: '#2e6b48', border: '#2e6b48', color: '#fbfdfb', tag: 'button' },
  input:   { bg: '#ffffff', border: '#b0b0a8', color: '#6b6b64', tag: 'div' },
  image:   { bg: '#f2f2ef', border: '#b0b0a8', color: '#6b6b64', tag: 'figure' },
  text:    { bg: 'transparent', border: '#d0d0c8', color: '#1a1a17', tag: 'p' },
  divider: { bg: '#e5e5e0', border: '#e5e5e0', color: '#6b6b64', tag: 'hr' },
}

function elementToHTML(el: WireframeElement): string {
  const s = ELEMENT_STYLE[el.type] ?? ELEMENT_STYLE.main
  const style = [
    `position:absolute`,
    `left:${el.x}px`,
    `top:${el.y}px`,
    `width:${el.width}px`,
    `height:${el.height}px`,
    `background:${s.bg}`,
    `border:1.5px solid ${s.border}`,
    `border-radius:4px`,
    `color:${s.color}`,
    `display:flex`,
    `align-items:center`,
    `justify-content:center`,
    `flex-direction:column`,
    `gap:4px`,
    `font-family:'Sora',sans-serif`,
    `font-size:${Math.min(13, Math.max(9, el.height * 0.16))}px`,
    `font-weight:500`,
    `text-align:center`,
    `padding:0 8px`,
    `box-sizing:border-box`,
    `overflow:hidden`,
  ].join(';')

  const tag = s.tag === 'hr' ? 'div' : s.tag
  const sizeLabel = `<span style="font-size:9px;opacity:0.4;font-family:'Space Mono',monospace;margin-top:2px">${el.width}×${el.height}</span>`
  const content = `<span>${el.label}</span>${el.height > 48 ? sizeLabel : ''}`

  return `    <${tag} data-type="${el.type}" aria-label="${el.label}" style="${style}">\n      ${content}\n    </${tag}>`
}

export function exportHTML(frame: WireframeFrame): string {
  const elements = frame.elements.map(elementToHTML).join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${frame.name} — Wireframe</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600&family=Space+Mono:wght@400&display=swap" rel="stylesheet" />
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: #f2f2ef;
      display: flex;
      align-items: flex-start;
      justify-content: center;
      min-height: 100vh;
      padding: 40px;
      font-family: 'Sora', sans-serif;
    }
    .wireframe-meta {
      position: fixed;
      top: 16px;
      left: 16px;
      background: #fff;
      border: 1px solid #e5e5e0;
      border-radius: 8px;
      padding: 10px 14px;
      font-size: 11px;
      color: #6b6b64;
      font-family: 'Space Mono', monospace;
      line-height: 1.6;
      box-shadow: 0 2px 8px rgba(0,0,0,0.06);
    }
    .wireframe-meta strong { color: #1a1a17; font-size: 12px; }
    .frame {
      position: relative;
      width: ${frame.width}px;
      height: ${frame.height}px;
      background: #ffffff;
      box-shadow: 0 8px 48px rgba(0,0,0,0.12);
      border-radius: 4px;
      overflow: hidden;
      flex-shrink: 0;
    }
  </style>
</head>
<body>
  <div class="wireframe-meta">
    <strong>${frame.name}</strong><br />
    ${frame.width} × ${frame.height} px<br />
    ${frame.elements.length} elements<br />
    Generated by Layout Builder
  </div>

  <div class="frame" role="img" aria-label="${frame.name} wireframe">
${elements}
  </div>
</body>
</html>`
}

// ─── Markdown / coding-agent prompt export ──────────────────────────────────

const TYPE_DESCRIPTION: Record<WireframeElement['type'], string> = {
  header:  'Top header / app bar',
  nav:     'Navigation bar',
  sidebar: 'Side navigation panel',
  main:    'Main content area',
  hero:    'Hero / banner section',
  footer:  'Page footer',
  card:    'Content card',
  chart:   'Data chart / visualization',
  table:   'Data table',
  form:    'Form / input section',
  list:    'List / feed',
  modal:   'Modal / dialog overlay',
  grid:    'Grid layout section',
  button:  'Button / CTA',
  input:   'Input field',
  image:   'Image / media block',
  text:    'Text / copy block',
  divider: 'Visual divider / separator',
}

function pct(val: number, total: number) {
  return ((val / total) * 100).toFixed(1) + '%'
}

function describePosition(el: WireframeElement, frame: WireframeFrame): string {
  const parts: string[] = []
  if (el.y === 0) parts.push('top-anchored')
  else if (el.y + el.height === frame.height) parts.push('bottom-anchored')
  if (el.x === 0) parts.push('left edge')
  else if (el.x + el.width === frame.width) parts.push('right edge')
  if (el.width === frame.width) parts.push('full width')
  if (el.height === frame.height) parts.push('full height')
  return parts.length ? ` (${parts.join(', ')})` : ''
}

export function exportMarkdown(frame: WireframeFrame): string {
  const date = new Date().toISOString().split('T')[0]
  const isHorizontal = frame.width > frame.height

  const sorted = [...frame.elements].sort((a, b) => a.y - b.y || a.x - b.x)

  const elementRows = sorted
    .map((el, i) => {
      const desc = TYPE_DESCRIPTION[el.type] ?? el.type
      const pos = describePosition(el, frame)
      const wPct = pct(el.width, frame.width)
      const hPct = pct(el.height, frame.height)
      return `| ${i + 1} | \`${el.type}\` | **${el.label}** | ${el.x}, ${el.y} | ${el.width}×${el.height} (${wPct} × ${hPct}) | ${desc}${pos} |`
    })
    .join('\n')

  const componentList = sorted
    .map((el, i) => {
      const pos = describePosition(el, frame)
      return `### ${i + 1}. ${el.label}

- **Type:** \`${el.type}\`
- **Position:** x=${el.x}px, y=${el.y}px${pos}
- **Size:** ${el.width}×${el.height}px (${pct(el.width, frame.width)} wide, ${pct(el.height, frame.height)} tall)
- **Semantic tag:** \`<${ELEMENT_STYLE[el.type]?.tag ?? 'div'}>\`
- **Description:** ${TYPE_DESCRIPTION[el.type] ?? el.type}`
    })
    .join('\n\n')

  return `# Wireframe Spec: ${frame.name}

> Generated by [Layout Builder](https://github.com/muhamien/layout-builder) on ${date}.
> Hand this file to a coding agent to implement the layout.

---

## Overview

| Property | Value |
|----------|-------|
| Screen name | ${frame.name} |
| Dimensions | ${frame.width} × ${frame.height} px |
| Orientation | ${isHorizontal ? 'Landscape / Desktop' : 'Portrait / Mobile'} |
| Total elements | ${frame.elements.length} |

---

## Layout Map

| # | Type | Label | Position (x, y) | Size | Notes |
|---|------|-------|-----------------|------|-------|
${elementRows}

---

## Component Specs

${componentList}

---

## Implementation Instructions

You are a senior frontend engineer. Implement the screen described above as a **production-quality React component** following these rules:

### Tech stack
- **Framework:** React 19 + TypeScript (strict mode)
- **Styling:** Tailwind CSS v4 with the token set below
- **Components:** shadcn/ui (new-york style) — install with \`npx shadcn@latest add <component>\`
- **Icons:** lucide-react only
- **Fonts:** Sora (sans) + Space Mono (mono) via Google Fonts

### Design tokens (paste into your global CSS)
\`\`\`css
:root {
  --background: #fcfcfb; --foreground: #1a1a17;
  --card: #ffffff; --card-foreground: #1a1a17;
  --primary: #2e6b48; --primary-foreground: #fbfdfb;
  --secondary: #f2f2ef; --secondary-foreground: #1a1a17;
  --muted: #f2f2ef; --muted-foreground: #6b6b64;
  --accent: #e9f0ea; --accent-foreground: #234e36;
  --destructive: #ae4f33; --destructive-foreground: #fbfaf9;
  --border: #e5e5e0; --input: #e5e5e0; --ring: #2e6b48;
  --radius: 4px;
  --font-sans: 'Sora', sans-serif;
  --font-mono: 'Space Mono', monospace;
}
\`\`\`

### Layout rules
- Reproduce the element positions faithfully; use CSS Grid or absolute positioning for the outer shell, then flex/grid inside each section
- Frame dimensions (${frame.width}×${frame.height}) are the reference — make the layout **responsive** down to 320px wide
- Every element must have proper semantic HTML, ARIA labels, and visible focus rings
- Light **and** dark mode must work (toggle via \`.dark\` on \`<html>\`)
- No hardcoded hex colors — use only the tokens above via \`var(--token)\` or Tailwind utilities like \`bg-primary\`, \`text-muted-foreground\`
- No gradients, no heavy shadows — flat design; shadows only on floating overlays

### Deliverable
Return **one self-contained \`${slugify(frame.name)}Page.tsx\` file** that renders the full screen. Include realistic placeholder content (not just "Lorem ipsum") that fits the screen purpose.
`
}

function slugify(s: string) {
  return s
    .replace(/[^a-zA-Z0-9 ]/g, '')
    .trim()
    .split(/\s+/)
    .map((w, i) => (i === 0 ? w.charAt(0).toUpperCase() + w.slice(1) : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('')
}

// ─── Helpers ────────────────────────────────────────────────────────────────

export function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function toSlug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
